version: "3.9"


services:
  psql_database:
    image: postgres:alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment: 
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: on-failure

  redis_mq:
    image: redis:alpine
    restart: on-failure
  
  web:
    build: .
    command: 
      - /bin/bash
      - -c
      - |
        uvicorn app.main:app --reload --host 0.0.0.0 \
        --port 5000 --access-log --log-level trace
    ports:
      - "5000:5000"
    depends_on:
      - psql_database
      - redis_mq
